// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCqlBXMnP4jiArM8L6YmEcdbs4Ti3i2QQ',
    appId: '1:561107080660:web:f79feead369d02ebf27241',
    messagingSenderId: '561107080660',
    projectId: 'todolist-7ff13',
    authDomain: 'todolist-7ff13.firebaseapp.com',
    storageBucket: 'todolist-7ff13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7lvg30-XqRUCnlb-ymp3q9RsJiFxrJpM',
    appId: '1:561107080660:android:3f9370db41a183b6f27241',
    messagingSenderId: '561107080660',
    projectId: 'todolist-7ff13',
    storageBucket: 'todolist-7ff13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeJuJvFnfvqhvM3V3NGVr0QDqP4uhZmBo',
    appId: '1:561107080660:ios:1a88b9c666990704f27241',
    messagingSenderId: '561107080660',
    projectId: 'todolist-7ff13',
    storageBucket: 'todolist-7ff13.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeJuJvFnfvqhvM3V3NGVr0QDqP4uhZmBo',
    appId: '1:561107080660:ios:5fa072ec89cde7b2f27241',
    messagingSenderId: '561107080660',
    projectId: 'todolist-7ff13',
    storageBucket: 'todolist-7ff13.appspot.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
