// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnuu8XV_GsgUDy-sIlu04RCEaJQcjfm8Y',
    appId: '1:185840917647:web:a32f1b9bff30d8a56b64fa',
    messagingSenderId: '185840917647',
    projectId: 'contact-list-93f48',
    authDomain: 'contact-list-93f48.firebaseapp.com',
    storageBucket: 'contact-list-93f48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPJbDMORxHAuhZYcQ_G_7-ysoAk6VLKT0',
    appId: '1:185840917647:android:3043db2b52de57bd6b64fa',
    messagingSenderId: '185840917647',
    projectId: 'contact-list-93f48',
    storageBucket: 'contact-list-93f48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVn2Uu4ZTFw1xK4xas-kpDUkotNKNj0LE',
    appId: '1:185840917647:ios:3d785df81e6766746b64fa',
    messagingSenderId: '185840917647',
    projectId: 'contact-list-93f48',
    storageBucket: 'contact-list-93f48.appspot.com',
    iosBundleId: 'com.example.contactList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVn2Uu4ZTFw1xK4xas-kpDUkotNKNj0LE',
    appId: '1:185840917647:ios:f4e66bf349e46f736b64fa',
    messagingSenderId: '185840917647',
    projectId: 'contact-list-93f48',
    storageBucket: 'contact-list-93f48.appspot.com',
    iosBundleId: 'com.example.contactList.RunnerTests',
  );
}
