// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOeT62N9izca_k1mrgMsCuaaPL6nWfEBc',
    appId: '1:915890579603:web:0b333762c3cb5ed4ea8566',
    messagingSenderId: '915890579603',
    projectId: 'todoapp-251c1',
    authDomain: 'todoapp-251c1.firebaseapp.com',
    storageBucket: 'todoapp-251c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5iWQSiOt0alFq6Gm8kbJU53pK_-HJQaI',
    appId: '1:915890579603:android:d50f6f1ceb319568ea8566',
    messagingSenderId: '915890579603',
    projectId: 'todoapp-251c1',
    storageBucket: 'todoapp-251c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA__wv8Og_MQQH0haiV5wndC0sXSlhZNX0',
    appId: '1:915890579603:ios:92376b4bb325836aea8566',
    messagingSenderId: '915890579603',
    projectId: 'todoapp-251c1',
    storageBucket: 'todoapp-251c1.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA__wv8Og_MQQH0haiV5wndC0sXSlhZNX0',
    appId: '1:915890579603:ios:dadae0a8140636bdea8566',
    messagingSenderId: '915890579603',
    projectId: 'todoapp-251c1',
    storageBucket: 'todoapp-251c1.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
