// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtblJuuVSqUvPjgta5vXzz3KIOrE6RN2M',
    appId: '1:387876428310:web:9e270b2dadf0405f73f337',
    messagingSenderId: '387876428310',
    projectId: 'form-dev-1',
    authDomain: 'form-dev-1.firebaseapp.com',
    storageBucket: 'form-dev-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJPbpdxq-CQy5sGhw7QauXlIzaMts74Pg',
    appId: '1:387876428310:android:0fdba9c744202b7473f337',
    messagingSenderId: '387876428310',
    projectId: 'form-dev-1',
    storageBucket: 'form-dev-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqdktK45e9PFzEQ-QbkjAwqusM5ccWmnU',
    appId: '1:387876428310:ios:59be6590563949fb73f337',
    messagingSenderId: '387876428310',
    projectId: 'form-dev-1',
    storageBucket: 'form-dev-1.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqdktK45e9PFzEQ-QbkjAwqusM5ccWmnU',
    appId: '1:387876428310:ios:1b05cc25b657668473f337',
    messagingSenderId: '387876428310',
    projectId: 'form-dev-1',
    storageBucket: 'form-dev-1.appspot.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
